services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver
    # startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: admin_project.settings
      - key: DATABASE_URL
        value:  'postgresql://neondb_owner:npg_Su3JRTi1hZkg@ep-ancient-truth-a8ssvv4v-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require'
      # - key: SECRET_KEY
      #   value: your-secret-key



